[server]
host = dtn.nersc
ssh_key_certificate = ~/.ssh/nersc-cert.pub
socket_transport = direct

working_directory = /global/cfs/projectdirs/m3239/pnorbert/streamdatain/bapsf_interferometer
python = ../.venv/bin/python3
script = streamer/consumer.py
compression_config = blosc2-zstd.conf

connection_file = ../data/logs/bobby-interf-direct.conn.json
output_directory = ../data/data/bobby-interf-direct
file_interval_seconds = 3600
stdout_log = ../data/logs/bobby-interf-direct.consumer.stdout.log
pid_file = ../data/logs/bobby-interf-direct.consumer.pid
timing_log = ../data/logs/bobby-interf-direct.consumer.jsonl

public_key = ../keys/testkey.pub
allow_ip_range = 169.232.151.52/32
port = 8501-8599
bind_host = 0.0.0.0
advertise_host = dtn.nersc.gov

socket_timeout_seconds = 60
startup_timeout_seconds = 60
retry_delay_seconds = 15
max_relaunch_attempts = 0

ntfy_topic_info = mock_data_streamer_nersc_info
ntfy_topic_alert = mock_data_streamer_nersc_alert
